# Generated by Django 3.1.7 on 2021-03-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
    ]
