# Generated by Django 3.1.7 on 2021-03-09 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_auto_20210309_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_city',
            field=models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '广州'), (3, '深圳')], default=0, verbose_name='工作地点'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(default='填写职位名称...', max_length=250, verbose_name='职位名称'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_requirement',
            field=models.TextField(default='填写职位要求描述...', max_length=1024, verbose_name='职位要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_responsibility',
            field=models.TextField(default='填写职责描述...', max_length=1024, verbose_name='职位职责'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.SmallIntegerField(choices=[(0, '技术类'), (1, '产品类'), (2, '运营类'), (3, '设计类')], default=0, verbose_name='职位类别'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
